/**
 * Tags API functions
 * Requirements: 23.1, 23.2
 */
import { apiClient } from "./client";
import type { Tag } from "@/types";

interface TagResponse {
  id: string;
  name: string;
  color: string;
  is_auto_generated: boolean;
  document_count: number;
}

// Extended Tag type with document count
export interface TagWithCount extends Tag {
  documentCount: number;
}

// Transform API response to frontend Tag type
function transformTag(data: TagResponse): TagWithCount {
  return {
    id: data.id,
    name: data.name,
    color: data.color,
    isAutoGenerated: data.is_auto_generated,
    documentCount: data.document_count,
  };
}

/**
 * List all tags for a storage
 * Requirements: 23.2
 */
export async function listTags(storageId: string): Promise<TagWithCount[]> {
  const response = await apiClient.get<TagResponse[]>("/tags", {
    storage_id: storageId,
  });
  return response.map(transformTag);
}

/**
 * Get a specific tag
 * Requirements: 23.2
 */
export async function getTag(tagId: string): Promise<TagWithCount> {
  const response = await apiClient.get<TagResponse>(`/tags/${tagId}`);
  return transformTag(response);
}

/**
 * Create a new tag
 * Requirements: 23.1
 */
export async function createTag(
  storageId: string,
  name: string,
  color?: string
): Promise<TagWithCount> {
  const payload: Record<string, string> = {
    storage_id: storageId,
    name,
  };
  if (color) {
    payload.color = color;
  }
  const response = await apiClient.post<TagResponse>("/tags", payload);
  return transformTag(response);
}

/**
 * Update a tag
 * Requirements: 23.1
 */
export async function updateTag(
  tagId: string,
  data: { name?: string; color?: string }
): Promise<TagWithCount> {
  const response = await apiClient.put<TagResponse>(`/tags/${tagId}`, data);
  return transformTag(response);
}

/**
 * Delete a tag
 * Requirements: 23.1
 */
export async function deleteTag(tagId: string): Promise<void> {
  await apiClient.delete(`/tags/${tagId}`);
}

/**
 * Update tags for a document
 * Requirements: 23.1, 23.2
 */
export async function updateDocumentTags(
  documentId: string,
  tagNames: string[]
): Promise<void> {
  await apiClient.put(`/documents/${documentId}/tags`, { tags: tagNames });
}

/**
 * Add a single tag to a document
 * Requirements: 23.1
 */
export async function addDocumentTag(
  documentId: string,
  tagName: string
): Promise<void> {
  await apiClient.post(
    `/documents/${documentId}/tags/${encodeURIComponent(tagName)}`
  );
}

/**
 * Remove a tag from a document
 * Requirements: 23.1
 */
export async function removeDocumentTag(
  documentId: string,
  tagName: string
): Promise<void> {
  await apiClient.delete(
    `/documents/${documentId}/tags/${encodeURIComponent(tagName)}`
  );
}
