// Storage types
export interface Storage {
  id: string;
  name: string;
  documentCount: number;
  totalSize: number;
  createdAt: Date;
  updatedAt: Date;
}

// Document types
export type DocumentType = "txt" | "pdf" | "docx" | "md" | "image";

export interface Document {
  id: string;
  storageId: string;
  folderId?: string;
  name: string;
  type: DocumentType;
  size: number;
  content?: string;
  tags: Tag[];
  isFavorite: boolean;
  isArchived: boolean;
  hasOcrText?: boolean; // Requirements: 10.1, 10.2 - OCR text extraction
  ocrText?: string; // OCR extracted text (only included when requested)
  createdAt: Date;
  updatedAt: Date;
  versions: Version[];
}

export interface Version {
  id: string;
  documentId: string;
  versionNumber: number;
  size: number;
  createdAt: Date;
  createdBy: string;
}

export interface Folder {
  id: string;
  storageId: string;
  parentId?: string;
  name: string;
  children: Folder[];
}

export interface Tag {
  id: string;
  name: string;
  color: string;
  isAutoGenerated: boolean;
  documentCount?: number;
}

// Search types
export interface SearchResult {
  documentId: string;
  documentName: string;
  snippet: string;
  score: number;
  highlights: string[];
}

// Chat types
export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: DocumentReference[];
  timestamp: Date;
}

export interface DocumentReference {
  documentId: string;
  documentName: string;
  snippet: string;
}

// User types
export interface User {
  id: string;
  email: string;
  name: string;
  role: "admin" | "editor" | "viewer";
  preferences: UserPreferences;
  twoFactorEnabled: boolean;
}

export interface UserPreferences {
  theme: "light" | "dark" | "system";
  language: string;
  fontSize: number;
  shortcuts: Record<string, string>;
}

// Collaboration types
export interface Comment {
  id: string;
  documentId: string;
  userId: string;
  content: string;
  parentId?: string;
  createdAt: Date;
}

export interface ShareLink {
  id: string;
  documentId: string;
  url: string;
  password?: string;
  expiresAt?: Date;
  accessCount: number;
}

export interface Webhook {
  id: string;
  url: string;
  events: string[];
  isActive: boolean;
}

export interface ActivityLog {
  id: string;
  userId: string;
  action: string;
  resourceType: string;
  resourceId: string;
  details: Record<string, unknown>;
  timestamp: Date;
}

// Notification types
export type NotificationType =
  | "document_shared"
  | "document_updated"
  | "document_commented"
  | "document_mentioned"
  | "user_joined"
  | "comment_reply"
  | "system_announcement"
  | "storage_limit"
  | "ai_task_complete"
  | "ai_tags_generated";

export interface Notification {
  id: string;
  user_id: string;
  type: NotificationType;
  type_description: string;
  title: string;
  message?: string;
  resource_type?: string;
  resource_id?: string;
  resource_name?: string;
  is_read: boolean;
  created_at: string;
  read_at?: string;
}

export interface NotificationsResponse {
  notifications: Notification[];
  unread_count: number;
  limit: number;
  offset: number;
}
